package wsvintsitsky.shortener.dataaccess.network.dtobject;

public enum RequestCommand {
	ACCOUNT_GET, ACCOUNT_GET_ALL, ACCOUNT_INSERT, ACCOUNT_UPDATE, ACCOUNT_DELETE, ACCOUNT_DELETE_ALL, ACCOUNT_GET_BY_EMAIL_AND_PASSWORD, ACCOUNT_FIND_NOT_NOTIFIED, ACCOUNT_DELETE_NOT_CONFIRMED, ACCOUNT_CONFIRM_USER,
	
	URL_GET, URL_GET_ALL, URL_INSERT, URL_UPDATE, URL_DELETE, URL_DELETE_ALL, URL_GET_URL_BY_SHORTURL, URL_GET_URLS_BY_IDS, URL_GET_URLS_BY_ACCOUNT_ID, URL_CHECK_OWNERSHIP,
	
	TAG_GET, TAG_GET_ALL, TAG_INSERT, TAG_UPDATE, TAG_DELETE, TAG_DELETE_ALL, TAG_GET_BY_TAG_DESCRIPTION, TAG_GET_EXISTING_TAGS, TAG_GET_BY_IDS,
	
	URL2TAG_INSERT_URL2TAGS_BY_URL, URL2TAG_INSERT_NEW_URL2TAGS_BY_URL, URL2TAG_DELETE_ALL, URL2TAG_DELETE_URL2TAGS_BY_URL, URL2TAG_DELETE_URL2TAGS_BY_TAG, URL2TAG_DELETE_OUTDATED_URL2TAGS_BY_URL, URL2TAG_GET_MATCHING_URL2TAGS_BY_URL, URL2TAG_GET_MATCHING_URL2TAGS_BY_TAG;
}
